path:
  train_data: ../data/doc.train.json # 改为训练数据文件位置
  test_data: ../data/doc.dev.json
  test_data_new: ../data/version2.doc.dev.json
  train_data_para: ../data/para.train.json # 改为训练数据文件位置
  train_data_sent: ../data/train.v1.53019.0.1.json # 改为训练数据文件位置
  test_data_para: ../data/para.dev.json
  test_data_para_new: ../data/version2.para.search.dev.json
  test_data_sent_new: ../data/valid.441.2.5.json
  model_file: ../models/sample_ft1.model # 改为模型所在位置


params:
  gpu: 0
  gra: para
  epoch: 500 # 训练轮次
  intv: 2000
  thread: 5 # 训练使用的CPU数目
  choice: 1
  chinese: bert-base-chinese
  english: bert-base-uncased
  hidden: 768
  embedding: 768
  res: 1
  batch_size: 32
  learning_rate: 5e-5
serve:
  port: 12345 # 服务端口号
  n_process: 1 # 进程数
